server:
  port: 8081

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/workforce
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: test123
    type: com.zaxxer.hikari.HikariDataSource
